/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Clases.Log;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zirex
 */
public class internalGestionCuentas extends Interfaz {
    private DefaultTableModel modeloTabla;

    /**
     * Creates new form internalGestionCuentas
     */
    public internalGestionCuentas() {
        initComponents();
        tabla.setModel(Log.getSusos());
        modeloTabla= (DefaultTableModel) tabla.getModel();
    }
    
    private boolean validarCampos(){
        boolean error= false;
        if(txtNombre.getText().trim().isEmpty()){
            showError(txtNombre, "Por favor digite el nombre del nuevo usuario.");
            error= true;
        }
        if(txtUserName.getText().isEmpty() || txtUserName.getText().trim().split(" ").length == 2){
            showError(txtUserName, "Por favor digite un nombre de usuario sin espacios.");
            error= true;
        }
        if(txtClave.getText().trim().isEmpty() || txtClave.getText().trim().split(" ").length == 2){
            showError(txtClave, "Por favor digite una clave sin espacios.");
            error=true;
        }
        return error;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpmTabla = new javax.swing.JPopupMenu();
        jmiEliminar = new javax.swing.JMenuItem();
        jmiCambiarClave = new javax.swing.JMenuItem();
        contenedor = new javax.swing.JPanel();
        panelDatos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtClave = new javax.swing.JTextField();
        panelTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        panelBotones = new javax.swing.JPanel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        jmiEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/borrar24x24.png"))); // NOI18N
        jmiEliminar.setText("Eliminar");
        jmiEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEliminarActionPerformed(evt);
            }
        });
        jpmTabla.add(jmiEliminar);

        jmiCambiarClave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar20px.png"))); // NOI18N
        jmiCambiarClave.setText("Cambiar clave");
        jmiCambiarClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCambiarClaveActionPerformed(evt);
            }
        });
        jpmTabla.add(jmiCambiarClave);

        setClosable(true);
        setIconifiable(true);
        setTitle("Gesto de cuentas");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        contenedor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        contenedor.setLayout(new javax.swing.BoxLayout(contenedor, javax.swing.BoxLayout.PAGE_AXIS));

        panelDatos.setLayout(new java.awt.GridLayout(4, 2));

        jLabel1.setText("Nombres y Apellidos:");
        panelDatos.add(jLabel1);

        txtNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreFocusLost(evt);
            }
        });
        panelDatos.add(txtNombre);

        jLabel2.setText("UserName:");
        panelDatos.add(jLabel2);

        txtUserName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUserNameFocusLost(evt);
            }
        });
        panelDatos.add(txtUserName);

        jLabel3.setText("Clave:");
        panelDatos.add(jLabel3);

        txtClave.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtClaveFocusLost(evt);
            }
        });
        panelDatos.add(txtClave);

        contenedor.add(panelDatos);

        panelTabla.setLayout(new javax.swing.BoxLayout(panelTabla, javax.swing.BoxLayout.LINE_AXIS));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla.setComponentPopupMenu(jpmTabla);
        jScrollPane1.setViewportView(tabla);

        panelTabla.add(jScrollPane1);

        contenedor.add(panelTabla);

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar32px.png"))); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        panelBotones.add(btnAceptar);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        panelBotones.add(btnCancelar);

        contenedor.add(panelBotones);

        getContentPane().add(contenedor);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        if(validarCampos()){
            JOptionPane.showMessageDialog(this, "Por favor verifique que los campos esten correctos.", "adBiblioteca", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        String nombreBibliotecario= txtNombre.getText().trim();
        String userName= txtUserName.getText().trim();
        char [] pass= txtClave.getText().trim().toCharArray();
        Log suso= Log.existe(userName);
        if(suso == null){
            Log nuevoUsuario= new Log(nombreBibliotecario, userName, pass);
            if(nuevoUsuario.insertarRol()){
                JOptionPane.showMessageDialog(this, "Exito... Se registro un nuevo usuario de la aplicación.", "adBiblioteca", JOptionPane.INFORMATION_MESSAGE);
                tabla.setModel(Log.getSusos());
            }
        }
       else{
            JOptionPane.showMessageDialog(this, "El userName ya existe por favor verifique que el usuario no haya sido creado\n"
                                                +"o utilice otro userName para crear la cuenta",
                                          "adBiblioteca", JOptionPane.INFORMATION_MESSAGE);
       }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void txtNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreFocusLost
        if(!txtNombre.getText().trim().isEmpty()){
            normalizeInput(txtNombre);
        }
    }//GEN-LAST:event_txtNombreFocusLost

    private void txtUserNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserNameFocusLost
        // TODO add your handling code here:
        if(!txtUserName.getText().trim().isEmpty() && txtUserName.getText().trim().split(" ").length == 1){
            normalizeInput(txtUserName);
        }
    }//GEN-LAST:event_txtUserNameFocusLost

    private void txtClaveFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtClaveFocusLost
        if(!txtClave.getText().trim().isEmpty() && txtClave.getText().trim().split(" ").length == 1){
            normalizeInput(txtClave);
        }
    }//GEN-LAST:event_txtClaveFocusLost

    private void jmiEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEliminarActionPerformed
        int [] rows = tabla.getSelectedRows();
        int len= rows.length -1;
        if(len != -1){
            for (; len >= 0; len--) {
                int row= rows[len];
                if(Log.eliminarRol(tabla.getValueAt(row, 0).toString()))
                    modeloTabla.removeRow(row);
            }
        }
    }//GEN-LAST:event_jmiEliminarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jmiCambiarClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCambiarClaveActionPerformed
        int fila= tabla.getSelectedRow();
        if(fila>-1){
            String username= tabla.getValueAt(fila, 2).toString();
            new GuiConfigUser(null, true, username).setVisible(true);
        }
    }//GEN-LAST:event_jmiCambiarClaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JPanel contenedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem jmiCambiarClave;
    private javax.swing.JMenuItem jmiEliminar;
    private javax.swing.JPopupMenu jpmTabla;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel panelTabla;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
