/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Clases.Log;
import javax.swing.JOptionPane;

/**
 *
 * @author zirex
 */
public class internalConfigUser extends javax.swing.JInternalFrame {
    private Log log;

    /**
     * Creates new form internalConfigUser
     */
    public internalConfigUser(Log log) {
        initComponents();
        this.log= log;
    }
    
    private char[] validarContraseña(){
        if(!this.txtPass1.getText().isEmpty() && !this.txtPass2.getText().isEmpty()){
            char[] pass1= this.txtPass1.getPassword();
            char[] pass2= this.txtPass2.getPassword();
            if(pass1.length == pass2.length){
                for (int i = 0; i < pass1.length; i++) {
                    if(pass1[i] != pass2[i]){
                        return null;
                    }
                }
            }
            return pass1;
        }
        else{
            return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JPanel();
        datos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPass1 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        txtPass2 = new javax.swing.JPasswordField();
        botones = new javax.swing.JPanel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Configuración de login");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        contenedor.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Gestion de Login"));
        contenedor.setLayout(new javax.swing.BoxLayout(contenedor, javax.swing.BoxLayout.PAGE_AXIS));

        datos.setLayout(new java.awt.GridLayout(2, 2));

        jLabel1.setText("Nueva contraseña");
        datos.add(jLabel1);
        datos.add(txtPass1);

        jLabel2.setText("Vuelve a escribir la nueva contraseña");
        datos.add(jLabel2);
        datos.add(txtPass2);

        contenedor.add(datos);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        botones.add(btnAceptar);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        botones.add(btnCancelar);

        contenedor.add(botones);

        getContentPane().add(contenedor);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        char[] pass= this.validarContraseña();
        if(pass!=null){
            this.log.setPass(pass);
            JOptionPane.showMessageDialog(this, "Exito... Cambio de contraseña exitoso.", "adBiblioteca", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        }   
        else{
            this.txtPass1.setText(null);
            this.txtPass2.setText(null);
            JOptionPane.showMessageDialog(this, "Por favor vuelva a escribir correctamente las nuevas contraseñas", "adBiblioteca", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botones;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JPanel contenedor;
    private javax.swing.JPanel datos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField txtPass1;
    private javax.swing.JPasswordField txtPass2;
    // End of variables declaration//GEN-END:variables
}
