/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Clases.Lector;

/**
 *
 * @author zirex
 */
public class internalLector extends Interfaz {
    private Lector lector = new Lector();
    private Principal principal;
    private internalUsuario iusuario;

    /**
     * Creates new form internalVisitante
     */
    public internalLector(Principal principal, internalUsuario iusuario) {
        initComponents();
        this.principal = principal;
        this.iusuario = iusuario;
        this.cargarPanelLector();
    }
    
    public void registrarUsuario(){
        if(this.principal.estaCerrado(this.iusuario)){
            this.iusuario = new internalUsuario();
            this.principal.panel.add(this.iusuario);
            this.iusuario.show();
        }
        else{
            this.iusuario.moveToFront();
        }
    }
    
    private void cargarPanelLector(){
        PanelLector pl = new PanelLector(this);
        pl.setSize(525, 467);
        pl.setLocation(0, 0);
        
        this.contenedor.removeAll();
        this.contenedor.add(pl);
        pl.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JLayeredPane();

        setClosable(true);
        setIconifiable(true);
        setTitle("Registro de lectores");

        javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
        contenedor.setLayout(contenedorLayout);
        contenedorLayout.setHorizontalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 525, Short.MAX_VALUE)
        );
        contenedorLayout.setVerticalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLayeredPane contenedor;
    // End of variables declaration//GEN-END:variables
}
